### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by tgeorgel** [boxybird/inertia-wordpress#19] opened 2022-10-20 06:56 UTC
Hi there, first of all thanks for your amazing work !

I've seen you added the type="wordpress-plugin" in the `composer.json` on master so we can use composer to get the plugin, that's cool !

However, the plugin still expect use to run `composer install` inside the plugin :

![Capture d’écran 2022-10-20 à 08 51 50](https://user-images.githubusercontent.com/11785727/196877209-45240f8f-db3e-490f-b6de-485daaed6025.png)

Any idea how to fix this ?

Thanks !

**Comment by boxybird** [comment] 2022-10-20 12:37
Hey @tgeorgel, thanks for the kind words.

To be honest, a contributor added "type='wordpress-plugin'" in a previous PR and it's a feature I don't take advantage of, nor fully understand.

That said, assuming you've chose the install path from the README, the error your getting might be because the required `vendor/autoload.php` file doesn't exist in the root of your theme. Or plugin, if you went that direction.

Sorry if that comes off as basic "composer" advice. I'm just hoping for an easy win!

**Comment by mortensassi** [comment] 2022-10-20 12:50
@tgeorgel @boxybird I think now the problem is that since it is marked as a "wordpress-plugin", it will be automatically moved to the plugins-folder which requires a user to run `composer install` after installing. Not very convenient.

I guess you should remove the type declaration (again) in order to get this plugin moved into the vendors directory by default in order to make it work without any further steps. **PLUS** anyone who needs this plugin to be moved to the `plugins` directory should extend his/her composer.json like this:

```json
// composer.json created by roots/bedrock
"extra": {
    "installer-paths": {
      "web/app/mu-plugins/{$name}/": [
        "type:wordpress-muplugin",
        "advanced-custom-fields/advanced-custom-fields-pro",
        "bostondv/acf-ninja-forms",
        "wpackagist-plugin/timber-library",
        "wpackagist-plugin/svg-support",
        "mortensassi/acf-svg-icon",
        "ooksanen/acf-focuspoint",
        "vinkla/headache",
        "wpackagist-plugin/svg-support"
      ],
      "web/app/plugins/{$name}/": [
      "type:wordpress-plugin",
     "boxybird/inertia-wordpress" // <<--- here
      ],
      "web/app/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  },
  ```

**Closed** 2024-12-29 00:55 UTC
